# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 007454eea0f69b2ff87782f78e901b55e87b93ab1b1b7ee660343fa198a01ca71b04154cb1180e0ef684f55c0668f73e8a179c6754640f385d854d429195fe39

test:
  secret_key_base: 8eb9c2c00c2fb135ad622367e7245153d373130d6a2dd2126d6aed6aaaf22c048b52db254bb1927cfe8bd8c9ee26fc4dad1f7eaa661d1f3af557a87ecbd926ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
